ls:
  src/**:
    .js: kebab-case
    .jsx: kebab-case | PascalCase
    .ts: kebab-case
    .tsx: kebab-case | PascalCase
    .vue: kebab-case | PascalCase
    .css: kebab-case | point.case
    .less: kebab-case | point.case
    .scss: kebab-case | point.case

ignore:
  - .git
  - node_modules
