ls:
  src/**:
    # useToken.js | remote-search.js | index.config.js
    .js: camelCase | kebab-case | point.case
    .ts: camelCase | kebab-case | point.case
    # index.tsx | FormItem.tsx
    .jsx: camelCase | PascalCase
    .tsx: camelCase | PascalCase
    # auth-redirect.vue | FromItem.vue
    .vue: kebab-case | PascalCase
    # index.css | Index.css | index.module.css
    .css: kebab-case | PascalCase | point.case
    .less: kebab-case | PascalCase | point.case
    .scss: kebab-case | PascalCase | point.case

ignore:
  - ./src/.umi
  - ./src/locales
